login/urls.py
from django.urls import path
from .views import LoginUrl

urlpatterns = [
    path('', LoginUrl.as_view())
]

project/urls.py
from django.contrib import admin
from django.urls import path # , include
from django.conf.urls import include

urlpatterns = [
    # path('grappelli/', admin.site.urls),  # grapelli URLS
    path('admin/', admin.site.urls),  # admin site
    path('other/', include('other.urls')),
    path('login/', include('login.urls')),
    path('store/', include('store.urls')),
]

store/urls.py
from django.urls import path
from .views import CartView, ProductSingleView, ShopView

app_name = "store"

urlpatterns = [
    path('', ShopView.as_view(), name="shop"),
    path('cart/', CartView.as_view(), name="cart"),
    path('product/<int:id>/', ProductSingleView.as_view(), name='product')

]

store/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='static/products/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    updated_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Discount(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    value = models.IntegerField()
    date_begin = models.DateTimeField()
    date_end = models.DateTimeField()

    def __str__(self):
        return f"{self.product.name}_{self.value}%_{self.date_end}"

store/views.py
from django.views import View
from django.shortcuts import render
from django.db.models import OuterRef, Subquery, F, ExpressionWrapper, DecimalField, Case, When
from django.utils import timezone
from .models import Product, Discount


# Create your views here.
class CartView(View):
    def get(self, request):
        return render(request, 'store/cart.html')


class ProductSingleView(View):
    def get(self, request, id):
        data = {1: {'name': 'Bell Pepper',
                    'description': 'Bell Pepper',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-1.jpg'},
                2: {'name': 'Strawberry',
                    'description': 'Strawberry',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-2.jpg'},
                3: {'name': 'Green Beans',
                    'description': 'Green Beans',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-3.jpg'},
                4: {'name': 'Purple Cabbage',
                    'description': 'Purple Cabbage',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-4.jpg'},
                5: {'name': 'Tomatoe',
                    'description': 'Tomatoe',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-5.jpg'},
                6: {'name': 'Brocolli',
                    'description': 'Brocolli',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-6.jpg'},
                7: {'name': 'Carrots',
                    'description': 'Carrots',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-7.jpg'},
                8: {'name': 'Fruit Juice',
                    'description': 'Fruit Juice',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-8.jpg'},
                9: {'name': 'Onion',
                    'description': 'Onion',
                    'price': 120.00,
                    'rating': 5.0,
                    'url': 'store/images/product-9.jpg'},
                10: {'name': 'Apple',
                     'description': 'Apple',
                     'price': 120.00,
                     'rating': 5.0,
                     'url': 'store/images/product-10.jpg'},
                11: {'name': 'Garlic',
                     'description': 'Garlic',
                     'price': 120.00,

                     'rating': 5.0,
                     'url': 'store/images/product-11.jpg'},
                12: {'name': 'Chilli',
                     'description': 'Chilli',
                     'price': 120.00,
                     'rating': 5.0,
                     'url': 'store/images/product-12.jpg'}
                }
        return render(request, "store/product-single.html", context=data[id])


class ShopView(View):
    def get(self, request):
        discount_value = Case(When(discount__value__gte=0,
                                   discount__date_begin__lte=timezone.now(),
                                   discount__date_end__gte=timezone.now(),
                                   then=F('discount__value')),
                              default=0,
                              output_field=DecimalField(max_digits=10, decimal_places=2)
                              )
        # Создание запроса на расчёт цены со скидкой
        price_with_discount = ExpressionWrapper(
            F('price') * (100.0 - F('discount_value')) / 100.0,
            output_field=DecimalField(max_digits=10, decimal_places=2)
        )

        products = Product.objects.annotate(
            discount_value=discount_value,
            # Другой способ через запрос в другую таблицу, однако
            # без фильтрации по времени действия скидки
            # discount_value=Subquery(
            #     Discount.objects.filter(product_id=OuterRef('id')).values(
            #         'value')
            # ),
            price_before=F('price'),
            price_after=price_with_discount
        ).values('id', 'name', 'image', 'price_before', 'price_after',
                 'discount_value')
        return render(request, 'store/shop.html', {"data": products})


        # context = {'data': [{'name': 'Bell Pepper',
        #                      'id': 1,
        #                      'discount': 30,
        #                      'price_before': 120.00,
        #                      'price_after': 80.00,
        #                      'url': 'store/images/product-1.jpg'},
        #                     {'name': 'Strawberry',
        #                      'id': 2,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-2.jpg'},
        #                     {'name': 'Green Beans',
        #                      'id': 3,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-3.jpg'},
        #                     {'name': 'Purple Cabbage',
        #                      'id': 4,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-4.jpg'},
        #                     {'name': 'Tomatoe',
        #                      'id': 5,
        #                      'discount': 30,
        #                      'price_before': 120.00,
        #                      'price_after': 80.00,
        #                      'url': 'store/images/product-5.jpg'},
        #                     {'name': 'Brocolli',
        #                      'id': 6,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-6.jpg'},
        #                     {'name': 'Carrots',
        #                      'id': 7,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-7.jpg'},
        #                     {'name': 'Fruit Juice',
        #                      'id': 8,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-8.jpg'},
        #                     {'name': 'Onion',
        #                      'id': 9,
        #                      'discount': 30,
        #                      'price_before': 120.00,
        #                      'price_after': 80.00,
        #                      'url': 'store/images/product-9.jpg'},
        #                     {'name': 'Apple',
        #                      'id': 10,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-10.jpg'},
        #                     {'name': 'Garlic',
        #                      'id': 11,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-11.jpg'},
        #                     {'name': 'Chilli',
        #                      'id': 12,
        #                      'discount': None,
        #                      'price_before': 120.00,
        #                      'url': 'store/images/product-12.jpg'},
        #                     ]
        #            }
        #
        # return render(request, 'store/shop.html', context)

store/templates/store/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block header %}
  <head>
    <title>Vegefoods - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'store/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/animate.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/magnific-popup.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/ionicons.min.css'%}">

    <link rel="stylesheet" href="{% static 'store/css/bootstrap-datepicker.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/jquery.timepicker.css'%}">


    <link rel="stylesheet" href="{% static 'store/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/icomoon.css'%}">
    <link rel="stylesheet" href="{% static 'store/css/style.css'%}">
  </head>
  <body class="goto-here">
		<div class="py-1 bg-primary">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 1235 2355 98</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">youremail@email.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">3-5 Business days delivery &amp; Free Returns</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="#">Vegefoods</a>
	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
              	<li class="nav-item"><a class="nav-link" href="{% url 'store:shop' %}">Shop</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'store:cart' %}">Cart</a></li>
	          <li class="nav-item cta cta-colored"><a href="{% url 'store:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>[0]</a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
{% endblock %}

{% block content %}
{% endblock %}

{% block footer %}
    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Shop</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Journal</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
	                <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
	                <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
	                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">FAQs</a></li>
	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'store/js/jquery.min.js'%}"></script>
  <script src="{% static 'store/js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'store/js/popper.min.js'%}"></script>
  <script src="{% static 'store/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'store/js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'store/js/jquery.waypoints.min.js'%}"></script>
  <script src="{% static 'store/js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'store/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'store/js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'store/js/aos.js'%}"></script>
  <script src="{% static 'store/js/jquery.animateNumber.min.js'%}"></script>
  <script src="{% static 'store/js/bootstrap-datepicker.js'%}"></script>
  <script src="{% static 'store/js/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'store/js/google-map.js'%}"></script>
  <script src="{% static 'store/js/main.js'%}"></script>
{% endblock %}
{% block scripts %}
{% endblock %}
  </body>
</html>

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg'%});">
	<div class="container">
	<div class="row no-gutters slider-text align-items-center justify-content-center">
		<div class="col-md-9 ftco-animate text-center">
		<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Cart</span></p>
		<h1 class="mb-0 bread">My Cart</h1>
		</div>
	</div>
	</div>
</div>

<section class="ftco-section ftco-cart">
		<div class="container">
			<div class="row">
			<div class="col-md-12 ftco-animate">
				<div class="cart-list">
					<table class="table">
						<thead class="thead-primary">
							<tr class="text-center">
							<th>&nbsp;</th>
							<th>&nbsp;</th>
							<th>Product name</th>
							<th>Price</th>
							<th>Quantity</th>
							<th>Total</th>
							</tr>
						</thead>
						<tbody>
							<tr class="text-center">
							<td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
							
							<td class="image-prod"><div class="img" style="background-image:url({% static 'store/images/product-3.jpg'%});"></div></td>
							
							<td class="product-name">
								<h3>Bell Pepper</h3>
								<p>Far far away, behind the word mountains, far from the countries</p>
							</td>
							
							<td class="price">$4.90</td>
							
							<td class="quantity">
								<div class="input-group mb-3">
								<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
							</div>
							</td>
							
							<td class="total">$4.90</td>
							</tr><!-- END TR-->

							<tr class="text-center">
							<td class="product-remove"><a href="#"><span class="ion-ios-close"></span></a></td>
							
							<td class="image-prod"><div class="img" style="background-image:url({% static 'store/images/product-4.jpg'%});"></div></td>
							
							<td class="product-name">
								<h3>Bell Pepper</h3>
								<p>Far far away, behind the word mountains, far from the countries</p>
							</td>
							
							<td class="price">$15.70</td>
							
							<td class="quantity">
								<div class="input-group mb-3">
								<input type="text" name="quantity" class="quantity form-control input-number" value="1" min="1" max="100">
							</div>
							</td>
							
							<td class="total">$15.70</td>
							</tr><!-- END TR-->
						</tbody>
						</table>
					</div>
			</div>
		</div>
		<div class="row justify-content-end">
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Coupon Code</h3>
					<p>Enter your coupon code if you have one</p>
					<form action="#" class="info">
				<div class="form-group">
				<label for="">Coupon code</label>
				<input type="text" class="form-control text-left px-3" placeholder="">
				</div>
			</form>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Apply Coupon</a></p>
			</div>
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Estimate shipping and tax</h3>
					<p>Enter your destination to get a shipping estimate</p>
					<form action="#" class="info">
				<div class="form-group">
				<label for="">Country</label>
				<input type="text" class="form-control text-left px-3" placeholder="">
				</div>
				<div class="form-group">
				<label for="country">State/Province</label>
				<input type="text" class="form-control text-left px-3" placeholder="">
				</div>
				<div class="form-group">
				<label for="country">Zip/Postal Code</label>
				<input type="text" class="form-control text-left px-3" placeholder="">
				</div>
			</form>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Estimate</a></p>
			</div>
			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
				<div class="cart-total mb-3">
					<h3>Cart Totals</h3>
					<p class="d-flex">
						<span>Subtotal</span>
						<span>$20.60</span>
					</p>
					<p class="d-flex">
						<span>Delivery</span>
						<span>$0.00</span>
					</p>
					<p class="d-flex">
						<span>Discount</span>
						<span>$3.00</span>
					</p>
					<hr>
					<p class="d-flex total-price">
						<span>Total</span>
						<span>$17.60</span>
					</p>
				</div>
				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Proceed to Checkout</a></p>
			</div>
		</div>
		</div>
	</section>
{% endblock %}

store/templates/store/shop.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="hero-wrap hero-bread" style="background-image: url({% static 'store/images/bg_1.jpg'%});">
	<div class="container">
	  <div class="row no-gutters slider-text align-items-center justify-content-center">
		<div class="col-md-9 ftco-animate text-center">
			<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Products</span></p>
		  <h1 class="mb-0 bread">Products</h1>
		</div>
	  </div>
	</div>
  </div>

  <section class="ftco-section">
	  <div class="container">
		  <div class="row justify-content-center">
			  <div class="col-md-10 mb-5 text-center">
				  <ul class="product-category">
					  <li><a href="#" class="active">All</a></li>
					  <li><a href="#">Vegetables</a></li>
					  <li><a href="#">Fruits</a></li>
					  <li><a href="#">Juice</a></li>
					  <li><a href="#">Dried</a></li>
				  </ul>
			  </div>
		  </div>
		  <div class="row">
			  {% for product in data %}
			  <div class="col-md-6 col-lg-3 ftco-animate">
				  <div class="product">
					  <a href="{% url 'store:product' product.id %}" class="img-prod"><img class="img-fluid" src="/{{ product.image }}" alt="Colorlib Template">
						  {% if product.discount_value %}
						  <span class="status">{{product.discount_value}}%</span>
						  {% endif %}
						  <div class="overlay"></div>
					  </a>
					  <div class="text py-3 pb-4 px-3 text-center">
						  <h3><a href="#">{{product.name}}</a></h3>
						  <div class="d-flex">
							  <div class="pricing">
								  {% if product.discount_value %}
								  <p class="price"><span class="mr-2 price-dc">${{product.price_before}}</span><span class="price-sale">${{product.price_after}}</span></p>
								  {% else %}
								  <p class="price"><span>${{product.price_before}}</span></p>
								  {% endif %}
							  </div>
						  </div>
						  <div class="bottom-area d-flex px-3">
							  <div class="m-auto d-flex">
								  <a href="#" class="add-to-cart d-flex justify-content-center align-items-center text-center">
									  <span><i class="ion-ios-menu"></i></span>
								  </a>
								  <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
									  <span><i class="ion-ios-cart"></i></span>
								  </a>
								  <a href="#" class="heart d-flex justify-content-center align-items-center ">
									  <span><i class="ion-ios-heart"></i></span>
								  </a>
							  </div>
						  </div>
					  </div>
				  </div>
			  </div>
			  {% endfor %}
		  </div>
		  <div class="row mt-5">
		<div class="col text-center">
		  <div class="block-27">
			<ul>
			  <li><a href="#">&lt;</a></li>
			  <li class="active"><span>1</span></li>
			  <li><a href="#">2</a></li>
			  <li><a href="#">3</a></li>
			  <li><a href="#">4</a></li>
			  <li><a href="#">5</a></li>
			  <li><a href="#">&gt;</a></li>
			</ul>
		  </div>
		</div>
	  </div>
	  </div>
  </section>
{% endblock %}